### ISSUE TITLE
Ubuntu and NUC 

### ISSUE THREAD

**Issue by awb99** [rm-hull/skull-canyon#2]
Hi there! 

I have the Intel nuc since January. 

I recommend to install the intel graphic drivers.. Because when I did not then suddenly after day one week of working on it.. The monitor  would start flickering. This is on a 4k resolution. The flickering was gone after I installed the driver. 

Unfortunately for me only Ubuntu works currently. On Intel site they only have Ubuntu and fedora drivers.  And for me fedora drivers never really worked.

**Comment by rm-hull** [comment]
Hey. Yes I've been using the drivers from the intel site... Should probably update the readme to reflect that 😀
