### ISSUE TITLE
Question: Use of your information

### ISSUE THREAD

**Issue by CAProjects** [rm-hull/skull-canyon#4]
Hi 

This is more of a question than an issue. Would it be OK with you to use some of your information with what I am doing myself here https://github.com/CAProjects/skull-canyon-ubuntu/wiki

I am no expert in Linux and not everyone is, so as i am going though setting things up i decided to document it for myself to refer to in case i mess something up and have to start over

**Comment by rm-hull** [comment]
Yes, happy for you to reuse information. It would be nice (but not necessary) if you would provide a link back to this repo in your documents.
